[package]
name = "arch-package-list-fetcher"
version = "0.2.1"
edition = "2021"

[dependencies]
colored = "2"
http_req = "^0.13"
regex = "1.5"
rss = "2.0"
thiserror = "2"
toml = "0.8"
xdg = "^2.1"

[profile.release]
lto = true
opt-level = 's'
panic = 'abort'
