[package]
name = "arch-package-list-fetcher"
version = "0.2.1"
edition = "2021"

[dependencies]
colored = "3"
http_req = "^0.14"
regex = "1.5"
rss = "2.0"
thiserror = "2"
toml = "0.9"
xdg = "^3.0"

[profile.release]
lto = true
opt-level = 's'
panic = 'abort'
